### ISSUE TITLE
It is unclear how this program should be used

### ISSUE THREAD

**Issue by PeterSwinkels** [xesf/dgds-viewer#2]
Hi,

This looks like an interesting project. However, I'm afraid I don't know how to use it. Could you point me in the right direction?

Peter

**Comment by xesf** [comment]
Hi @PeterSwinkels ,

Follow the steps in the usage sessions here: https://github.com/xesf/dgds-viewer#usage

1. You will need NodeJS and Yarn installed.
2. Create a data folder with the games as specified here: https://github.com/xesf/dgds-viewer/issues/1
3. Run the following commands in the root directory of the project.
> yarn install

> yarn start

Let me know if you were able to run it.

**Comment by PeterSwinkels** [comment]
Hi @xesf,

Thank you for your quick reply. I tried your suggestions. I appear to get stuck at the "yarn start" command. I get the following error:

[0] Error: error:0308010C:digital envelope routines::unsupported
[0]     at new Hash (node:internal/crypto/hash:71:19)
[0]     at Object.createHash (node:crypto:133:10)
[0]     at module.exports (D:\Other\dgds-viewer-master\node_modules\webpack\lib\util\createHash.js:135:53)
[0]     at NormalModule._initBuildHash (D:\Other\dgds-viewer-master\node_modules\webpack\lib\NormalModule.js:417:16)
[0]     at handleParseError (D:\Other\dgds-viewer-master\node_modules\webpack\lib\NormalModule.js:471:10)
[0]     at D:\Other\dgds-viewer-master\node_modules\webpack\lib\NormalModule.js:503:5
[0]     at D:\Other\dgds-viewer-master\node_modules\webpack\lib\NormalModule.js:358:12
[0]     at D:\Other\dgds-viewer-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
[0]     at iterateNormalLoaders (D:\Other\dgds-viewer-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
[0]     at Array.<anonymous> (D:\Other\dgds-viewer-master\node_modules\loader-runner\lib\LoaderRunner.js:205:4) {
[0]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[0]   library: 'digital envelope routines',
[0]   reason: 'unsupported',
[0]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[0] }
[0]
[0] Node.js v18.13.0
[0] [nodemon] app crashed - waiting for file changes before starting...

**Comment by xesf** [comment]
Hi @PeterSwinkels 
I believe it could be the version of your NodeJs being too new.
Can you try using nodejs 12?

Before reinstalling you can try to delete the node_modules folder and use npm instead of yarn.

> npm install

> nom run start

I haven't testes this on a Windows machine but it should work fine.

Cheers,
Alex

**Comment by PeterSwinkels** [comment]
I got it to work. It lists the resources for my copy of Willy Beamish but doesn't display anything else. What exactly can your program do?

**Comment by xesf** [comment]
Glad it works.

For Willy Beamish nothing has been implemented yet, there are shared formats between the games but not all have been reversed. There are few types like BMP that should be ok to do, they must be a new version of that type.

I mainly focused on Johnny Castaway to create the viewer and there is still a lot to be done there.

**Comment by PeterSwinkels** [comment]
Aha, I see. Too bad. If you like I can give you some feedback on your project.

**Comment by xesf** [comment]
Happy to receive it.

**Comment by PeterSwinkels** [comment]
Alright, may I suggest that you:
1. Include a brief list of prerequisite software.
2. A short summary of how to use the software in question.
3. A basic manual indicating how to use the software.
?
